tasks:
  - slug: clean_litter
    name: "Cleaned litter box"
    icon: "ğŸ§¹"
    color: "amber"
  - slug: feed
    name: "Fed the cat"
    icon: "ğŸ½ï¸"
    color: "blue"
  - slug: change_sand
    name: "Changed litter sand"
    icon: "ğŸ–ï¸"
    color: "purple"
  - slug: give_meds
    name: "Gave medicine"
    icon: "ğŸ’Š"
    color: "red"
  - slug: clean_teeth
    name: "Gave teeth clean pulver"
    icon: "ğŸ¦·"
    color: "white"
  - slug: "playtime"
    name: "Played with the cats"
    icon: "ğŸ®"
    color: "green"