tasks:
  - slug: clean_litter
    name: "Katzenklo reinigen"
    order: 1
    icon: "ğŸ§¹"
    color: "amber"
  - slug: feed
    name: "FÃ¼ttern"
    order: 2
    icon: "ğŸ½ï¸"
    color: "blue"
  - slug: change_sand
    name: "Sand im Klo ausgetauscht"
    order: 3
    icon: "ğŸ–ï¸"
    color: "purple"
  - slug: clean_teeth
    name: "Zahnputzflocken geben"
    order: 4
    icon: "ğŸ¦·"
    color: "yellow"
  - slug: "playtime"
    name: "Spielen"
    order: 5
    icon: "ğŸ®"
    color: "green"
  - slug: "water_pump"
    name: "Wasserpumpe reinigen"
    order: 6
    icon: "ğŸŒŠ"
    color: "blue"
  - slug: "water_filter"
    name: "Wasserfilter wechseln"
    order: 7
    icon: "ğŸ’§"
    color: "amber"
