tasks:
  - slug: clean_litter
    name: "Katzenklo reinigen"
    icon: "ğŸ§¹"
    color: "amber"
  - slug: feed
    name: "FÃ¼ttern"
    icon: "ğŸ½ï¸"
    color: "blue"
  - slug: change_sand
    name: "Sand im Klo ausgetauscht"
    icon: "ğŸ–ï¸"
    color: "purple"
  - slug: clean_teeth
    name: "Zahnputzflocken geben"
    icon: "ğŸ¦·"
    color: "white"
  - slug: "playtime"
    name: "Spielen"
    icon: "ğŸ®"
    color: "green"